winglang/winglibs

containers/workload.sim.w
=> chore(containers): let docker decide on container id

bedrock/README.md, bedrock/package.json
Fix the main build (all changes to READMEs require version bumps)
=> chore: bump bedrock to 0.0.2

postgres/package.json
=> chore(postgres): bump version

.github/workflows/close-stale.yaml, generate-workflows.main.w, library.w, stale.w
Set up a workflow for auto-closing stale pull requests
=> chore: set up stale PR workflow

.github/workflows/pull-request-lint.yaml, .github/workflows/redis-pull.yaml, .mergify.yml, generate-workflows.main.w, mergify.w, pr-lint.w
=> chore: add mergify and pr lint workflows

bedrock/package-lock.json, containers/package-lock.json, containers/package.json, github/package-lock.json, postgres/package-lock.json, update-wing.sh, websockets/package-lock.json, websockets/package.json
- Updates wing to the latest version in each winglib.
- Adds a script to update wing (would be nice to do it in a cron job).
=> chore: update wing version

.github/workflows/sagemaker-pull.yaml, .github/workflows/sagemaker-release.yaml, .gitignore, .mergify.yml, sagemaker/.gitignore, sagemaker/LICENSE, sagemaker/README.md, sagemaker/package-lock.json, sagemaker/package.json, sagemaker/sagemaker.js, sagemaker/sagemaker.sim.w, sagemaker/sagemaker.test.w, sagemaker/sagemaker.tfaws.w, sagemaker/sagemaker.w, sagemaker/types.w
fixes: https://github.com/winglang/wing/issues/5565
@ekeren FYI
=> feat: `bring sagemaker`

.github/workflows/canary.yaml, canary.w, generate-workflows.main.w
Closes https://github.com/winglang/wing/issues/5263
=> chore(repo): set up canary

containers/package.json
Last PR forgot to update the version
=> fix(containers): cannot publish over existing version

vite/vite.w
=> feat(vite): vite endpoint on terraform outputs

ngrok/README.md, ngrok/ngrok.test.w, ngrok/ngrok.w
Use the shiny new array lifting to support `tunnel.onConnect()`.
=> feat(ngrok): `onConnect`

websockets/lib.w, websockets/package-lock.json, websockets/package.json
Hide the inner implementation and add a `url` field to wing console inspector.
=> fix(websockets): add url to wing console

vite/package.json, vite/vite.cjs, vite/vite.sim.w
Fixes https://github.com/winglang/wing/issues/5938
=> fix(vite): dev server isn't stopped after running tests

vite/package.json, vite/vite-plugin.mjs, vite/vite.sim.w
fixing path prefixed with a '/'
also stop using non exiting env vars on windows
=> fix(vite): vite resource doesn't work in windows

.github/workflows/canary.yaml, .github/workflows/dynamodb-release.yaml, canary.w, dynamodb/test.sh, library.w
https://winglang.slack.com/archives/C04AUK4P5N2/p1710945056297129?thread_ts=1710940443.922019&cid=C04AUK4P5N2
The canary tests of the dynamodb lib failed since we have a limit to the number of dockers we can run in parallel.
I committed a change to the yaml files- but since it's auto-generated it will be lost next time someone will be creating a new lib with the script.
So, as the last step of the process- I changed the script to accept an override, created an override for the dynamodb lib, and ran the scripts to verify :)
=> feat: add a test override script to customize test command

dynamodb/package.json
Fixes https://github.com/winglang/wing/issues/6005
=> fix(dynamodb): pack .mjs files

websockets/inflight/websocket.aws.extern.d.ts, websockets/lib.test.w, websockets/package-lock.json, websockets/package.json, websockets/platform/sim/wb.extern.d.ts, websockets/util.extern.d.ts
Update tests to use `dynamodb.Table` in place of the `ex.DynamodbTable` class.
=> chore(websockets): fix tests

eventbridge/package.json, eventbridge/platform/awscdk/eventbridge.w, eventbridge/platform/tfaws/eventbridge.w
Updates to library to use the new api for platform parameters.
=> fix(eventbridge): use new platform parameter api

dynamodb/dynamodb.extern.d.ts, dynamodb/dynamodb.mjs, dynamodb/dynamodb.sim.w, dynamodb/package-lock.json, dynamodb/package.json
No need to take a dependency on the messy `containers` library
=> chore(dynamodb): migrate to `sim.Container`

dynamodb/dynamodb.w, dynamodb/package.json
1. Hide underlying implementation
2. Add "Table Name" field
=> fix(dynamodb): improve ui

cognito/README.md, cognito/package.json
Improved the readme examples and now they compile and run successfully.
=> fix(cognito): docs compile and improved

dynamodb/package.json, dynamodb/tests/streams.test.w
Add a minimal test for streams
=> chore(dynamodb): minimal stream test

dynamodb/dynamodb.extern.d.ts, dynamodb/dynamodb.sim.w, dynamodb/package-lock.json, dynamodb/package.json
Use the DescribeTable operation on a table to ensure that the table is ready.
=> fix(dynamodb): ensure table is ready

.github/workflows/canary.yaml, canary.w
This action requires specifying either timeout_minutes or timeout_seconds inputs
=> chore: fix canary workflow

postgres/lib.w, postgres/package-lock.json, postgres/package.json
Done @skyrpex and @ekeren 
- Replaced `container.Workload` with `sim.container`
- Exposed client configuration 
- Upgrade default postgres version to 16
=> feat(postgres)!: public connection string, change default postgres version to 16

.github/workflows/canary.yaml, .github/workflows/cdk8s-pull.yaml, .github/workflows/cdk8s-release.yaml, .github/workflows/pull-request-lint.yaml, .mergify.yml, README.md, cdk8s/.gitignore, cdk8s/LICENSE, cdk8s/README.md, cdk8s/examples/nodejs-app/index.js, cdk8s/examples/nodejs.main.w, cdk8s/examples/ubuntu.main.w, cdk8s/lib/index.js, cdk8s/package-lock.json, cdk8s/package.json, cdk8s/test.sh
A custom platform for synthesizing k8s YAML using cdk8s:
Install:
```sh
npm i @winglibs/cdk8s cdk8s-plus-27
```
Code:
```js
// main.w
bring "cdk8s-plus-27" as k8s;
let d = new k8s.Deployment(replicas: 3);
d.addContainer(image: "ubuntu");
```
Compile:
```sh
wing compile -t @winglibs/cdk8s
```
=> feat: `bring cdk8s`

postgres/README.md, postgres/lib.w, postgres/package.json, postgres/pg.js
- Supports creating RDS postgres databases
- Support referencing existing databases using `DatabaseRef` class
- https://github.com/winglang/wing/pull/6377
- https://github.com/winglang/wing/pull/6345
=> feat(postgres): support AWS RDS

.github/workflows/python-pull.yaml, python/function.test.w, python/package-lock.json, python/package.json, python/sim/containers.w, python/sim/function.js, python/sim/inflight.w, python/test-assets/main.py, python/test-assets/wing.py, python/tfaws/function.js, python/util.extern.d.ts, python/util.js, python/wplatform.js
Changed base image to AWS official
Also fixed being able to set env vars on the function
=> chore(python): change base image

vite/package-lock.json, vite/package.json, vite/vite-types.w, vite/vite.sim.w
This PR adds an `openBrowser` prop to the Vite resource and sets it to false as default.
=> feat(vite): add `openBrowser` prop

dynamodb/dynamodb-types.w, dynamodb/dynamodb.sim.w, dynamodb/dynamodb.tf-aws.w, dynamodb/dynamodb.w, dynamodb/package-lock.json, dynamodb/package.json
Useful when accessing the table using native clients
=> feat(dynamodb): get table connection with read write permissions

slack/README.md
=> fix(slack): readme example did not compile

slack/package.json
I tried to add this to the last PR but it was a non blocking comment cause I goofed
=> fix(slack): update package version for last change

dynamodb/package.json, ses/package.json, sns/package.json
Build broken - bumping version...
=> chore(repo): version bump

.github/workflows/canary.yaml, .github/workflows/cdk8s-pull.yaml, .github/workflows/cdk8s-release.yaml, .github/workflows/containers-pull.yaml, .github/workflows/containers-release.yaml, .github/workflows/dynamodb-pull.yaml, .github/workflows/dynamodb-release.yaml, .github/workflows/react-pull.yaml, .github/workflows/react-release.yaml, .mkrepo/canary.w, .mkrepo/library.w, cdk8s/examples/nodejs.main.w, cdk8s/lib/index.js, cdk8s/package-lock.json, cdk8s/package.json, cdk8s/root.test.w, cdk8s/test.sh
Fixes https://github.com/winglang/wing/issues/6806
=> fix(cdk8s): unable to obtain root node

dynamodb/dynamodb.extern.d.ts, dynamodb/dynamodb.tf-aws.w, dynamodb/package.json
After merging https://github.com/winglang/wing/pull/6839
everything is passing:
=> fix: dynamodb optional json use

dynamodb/package-lock.json, dynamodb/package.json
The changes from https://github.com/winglang/winglibs/pull/290 were not released
=> chore(dynamodb): bump version

cdk8s/README.md, cdk8s/api-object.w, cdk8s/examples/api-object.main.w, cdk8s/examples/api-object.main.w.snap, cdk8s/examples/nodejs.main.w.snap, cdk8s/examples/ubuntu.main.w.snap, cdk8s/lib/index.js, cdk8s/root.test.w, cdk8s/test.sh
You can now use the `WING_K8S_LABELS` environment variable to add labels to all resources in an app.
=> feat(cdk8s): labels

.mergify.yml, .mkrepo/mergify.w
These fields have been deprecated (see https://docs.mergify.com/configuration/file-format/#pull-request-rules and https://raw.githubusercontent.com/Mergifyio/docs/main/public/mergify-configuration-schema.json)
=> chore: update mergify configuration

k8s/README.md, k8s/examples/api-object.main.w.snap, k8s/lib/index.js, k8s/package.json, k8s/test.sh
Allow specifying the default namespace for all objects within an app through an environment variable.
=> feat(k8s): default namespace

postgres/pg.js
Adjust the connection string encoding to handle optional port 
values.
=> fix(postgres): update connection string handling for optional port
