winglang/winglibs

.github/workflows/postgres-pull.yaml
.github/workflows/postgres-release.yaml
.github/workflows/postgres.yaml
.gitignore
postgres/README.md
postgres/lib.test.w
postgres/lib.w
postgres/package-lock.json
postgres/package.json
postgres/pg.js

Introduces a postgres `Database` resource. On cloud targets it uses [Neon](https://neon.tech/). Currently it only works on AWS because I want to inject a secret during deployment, and the current `cloud.Secret` resource doesn't support that, but it should be possible to make the cloud implementation cloud agnostic (so it works on GCP and Azure as well).
The simulator target should be able to use an ordinary postgres container, but I haven't implemented it yet as I think I need to use the `containers` library, which will introduces peer dependencies in this repo and... yeah.
Closes https://github.com/winglang/wing/issues/4914

feat: bring postgres

---

.github/workflows/bedrock-pull.yaml
.github/workflows/bedrock-release.yaml
bedrock/.gitignore
bedrock/LICENSE
bedrock/README.md
bedrock/api.w
bedrock/bedrock.js
bedrock/bedrock.sim.w
bedrock/bedrock.test.w
bedrock/bedrock.tfaws.w
bedrock/bedrock.w
bedrock/joke.test.w
bedrock/joke.w
bedrock/package-lock.json
bedrock/package.json

A Wing library for working with Amazon Bedrock.
Authors @ekeren, @eladb

feat(bedrock): introduce bedrock

---

fifoqueue/fifo-queue.aws.w
fifoqueue/package-lock.json
fifoqueue/package.json

The void return type is not correct now

fix(fifo-queue): wrong return type for cloud.Function in latest wing version

---

containers/ecr.main.w
containers/package-lock.json
containers/package.json
containers/tfaws-eks.w

Update containers to latest wing version, which requires a workaround for "not implemented"-esque throw

fix(containers): missing return type for cluster attributes in latest wing version

---

websockets/commons/api.w
websockets/lib.test.w
websockets/lib.w
websockets/package-lock.json
websockets/package.json
websockets/platform/awscdk.w
websockets/platform/sim.w
websockets/platform/tf-aws.w

BREAKING CHANGE: the `url()` and `inflightUrl()` methods have been removed in favor of a `url` property.

fix(websockets)!: fix token usage in simulator

---

bedrock/README.md
bedrock/bedrock.w
bedrock/joke.test.w
bedrock/package-lock.json
bedrock/package.json

replaced the use of BEDROCK_DEV with the utility function `isTestEnvironment`

chore(bedrock): replacing BEDROCK_DEV with isTestEnvironment

---

.github/workflows/bedrock-release.yaml
.github/workflows/checks-release.yaml
.github/workflows/containers-release.yaml
.github/workflows/fifoqueue-release.yaml
.github/workflows/github-release.yaml
.github/workflows/postgres-release.yaml
.github/workflows/redis-release.yaml
.github/workflows/websockets-release.yaml
library.w
postgres/package.json

Set up GitHub releases. This will be used to set up a webhook that detects newly released packages from GitHub release events.
Version bumped `postgres` for testing purposes

chore: set up GitHub releases

---

websockets/commons/api.w
websockets/lib.test.w
websockets/package-lock.json
websockets/package.json
websockets/platform/tf-aws.w

This PR includes:
- Adding missing void return types.
- Fix URL passed to sendMessage was not being properly built

fix: websocket sendMessage url

---

containers/aws.w
containers/ecr.main.w
containers/eks.main.w
containers/package-lock.json
containers/package.json
containers/tfaws-ecr.w
containers/tfaws-eks.w

Modernize the code and relax the peer dependencies to avoid issues.

chore(containers): modernize

---

checks/check.w
checks/package.json
sagemaker/package.json
sagemaker/sagemaker.test.w

Updating code in `sagemaker` and `checks` winglibs to work with the latest version of Wing.

fix: sagemaker and checks breakages

---

ngrok/ngrok.w
ngrok/util.js

Gathers the dirname during preflight so it can spawn the `ngrok.js` helper during inflight.

fix(ngrok): invalid relative path to `ngrok.js`

---

containers/containers.test.w
containers/package-lock.json

This test from `containers` is occasionally failing in CI, but the assertion isn't showing us why. Adding a log statement to help.
Not bumping the library version since releasing a new version isn't necessary here.

chore: add log statement for test debugging

---

vite/package.json
vite/vite-cli.mjs
vite/vite-plugin.mjs
vite/vite.sim.w

- Fixes the `wing` object format
- In some cases, such as adding a class to the `<head>` element in the `index.html`, would cause the Vite resource not being able to generate the `wing` environment object at all
- Stop opening the browser when Wing is running tests.

fix(vite): html transformation

---

vite/package.json
vite/vite.cjs

Vite bundles for production when `NODE_ENV=production`, which makes variables like `import.meta.env.DEV` equal to `true` even for production environments.

fix(vite): production build uses development variables

---

vite/package-lock.json
vite/package.json
vite/vite-plugin.mjs
vite/vite.tf-aws.w

- Improve `wing` object script injection by using Vite's tags API
- Add the `immutable` cache directive to assets
- Lower the default cache time for non-assets to 1m (eg, the `index.html` file)

fix(vite): improve `wing` script injection

---

containers/local-build.test.w
containers/package.json
containers/workload.sim.w
containers/workload.tfaws.w
fifoqueue/fifo-queue.aws.w
github/lib.test.w
github/package.json
websockets/package.json
websockets/platform/awscdk.w

Fixes to address changes to stringable in wing 0.61.0
Canary was failing: https://github.com/winglang/winglibs/actions/runs/8255038538

fix: updates for wing 0.61.0

---

fifoqueue/package.json

I forgot to update this one in my last PR

chore: update fifo-queue version

---

containers/package-lock.json
containers/package.json
containers/workload.sim.w

- Use `docker --rm --detach` along with a random container name
- Explicitly remove the container during `cloud.Service` destroy callback

fix(containers): ensure containers are destroyed when wing console is interrupted

---

.github/workflows/dynamodb-pull.yaml
.github/workflows/dynamodb-release.yaml

The Wing test runner will keep all docker containers while running the tests, which amounts to ~10 containers. I believe the CI runner runs out of memory because of this.

chore(dynamodb): execute tests in serial

---

containers/api.w
containers/ecr.main.w
containers/helm.extern.d.ts
containers/local-build.test.w
containers/package-lock.json
containers/package.json
containers/simple.test.w
containers/utils.extern.d.ts
containers/utils.js
containers/utils.w
containers/values.w
containers/workload.sim.w
containers/workload.tfaws.w
containers/workload.w

Use the shiny new `sim.Container` to implement the simulator version of `Workload`.
BREAKING CHANGE: `sources` is a glob string instead of an array of strings.

fix(containers)!: migrate to `sim.Container`

---

checks/package.json
checks/results.w

Maybe is a smell that we need `Struct.tryFromJson` but the core issue is the undefined object passed validation, which is surprising to me, but non the less there is some cleanup needed in Struct.fromJson since I made the changes to only return back the fields that match, and not the whole object.

fix(checks): latest does not check for nil

---

dynamodb/README.md
dynamodb/dynamodb-types.w
dynamodb/dynamodb.extern.d.ts
dynamodb/dynamodb.sim.w
dynamodb/dynamodb.tf-aws.w
dynamodb/dynamodb.w
dynamodb/package-lock.json
dynamodb/tests/connection.test.w
dynamodb/tests/name.test.w

`table.connection` now includes `clientConfig` instead of just `endpoint`, so it can be used to create an AWS SDK client without any hacks.
I also changed it from a method to a property, so it can be lifted across inflight.
Added a `tableName` property with the name of the table.
Found a bug in `tf-aws` where `name` was not respected.
Tested on AWS.
BREAKING CHANGE: `table.connection()` (method) is now `table.connection` (property). The `connection.endpoint` attribute is now `connection.clientConfig.endpoint`.

feat(dynamodb)!: api tweaks

---

dynamodb/dynamodb.sim.w

There seems to be a bug where INSERT events aren't processed by the stream consumer (only for apps that have more than one table).
The workaround stops reusing the same host (and container) and instead creates one container per table.

fix(dynamodb): events of type "insert" not processed when multiple tables are present

---

jwt/lib.test.w
jwt/lib.w
jwt/package-lock.json
jwt/package.json
jwt/utils.extern.d.ts
jwt/utils.js

* change `mts` file to `js`
* add `decode` function which is not verifying the token

fix(jwt): package missing util file

---

dynamodb/dynamodb.sim.w
dynamodb/package.json

Now since the container might be reused across simulator updates, we need to make sure we clean up the table before it's being created.
I've tested this manually because I am not sure how to test this.

fix(dynamodb): cannot reuse container since table already exists

---

dynamodb/dynamodb.sim.w
dynamodb/package-lock.json
dynamodb/package.json

Previously, the simulator target would try to update the TTL of the table before waiting for the table to be ready.

fix(dynamodb): update table ttl after table is ready

---

react/api.w
react/package.json
react/sim.w
react/tf-aws.w
react/utils.extern.d.ts
react/utils.js
react/utils.w

Implement of https://github.com/winglang/wing/issues/6178
I also deleted `get-port` from the code, it causes a compilation error (in addition to not being used at the moment):
```
Error: require() of ES Module /Users/meir/Documents/GitHub/winglibs2/react/node_modules/get-port/index.js from /Users/meir/Documents/GitHub/winglibs2/react/utils.js not supported.
Instead change the require of index.js in /Users/meir/Documents/GitHub/winglibs2/react/utils.js to a dynamic import() which is available in all CommonJS modules.
```

feat(react): add custom domain

---

tsoa/README.md
tsoa/app-aws.js
tsoa/app.js
tsoa/clients.d.ts
tsoa/clients.js
tsoa/lib.w
tsoa/package-lock.json
tsoa/package.json
tsoa/sim.w
tsoa/test-assets/usersController.ts
tsoa/test/lib.test.w
tsoa/tfaws.w
tsoa/types.w

- Changes API from (`liftClient`, `getClient`) to  (`lift`, `lifted`)
- Lift API is now `service.lift(resource, id: "name", allow: ["action"])`. didn't use `as` because it is highlighted as a special keyword in the IDE
- Uses [asynclocalstorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) instead of req for storing and passing lifted clients context

feat(tsoa)!: new lift API

---

dynamodb/dynamodb-client.w
dynamodb/dynamodb-types.w
dynamodb/dynamodb.sim.w
dynamodb/package-lock.json
dynamodb/package.json
github/octokit/types.w
github/package-lock.json
github/package.json
github/probot/adapter.w
github/probot/types.w
github/simutils/simutils.w
jwt/lib.w
jwt/package-lock.json
jwt/package.json
ngrok/ngrok.w
ngrok/package-lock.json
ngrok/package.json
openai/openai.w
openai/package-lock.json
openai/package.json
redis/api.w
redis/package-lock.json
redis/package.json
redis/redis.extern.d.ts
tsoa/package-lock.json
tsoa/package.json
tsoa/sim.w
vite/package-lock.json
vite/package.json
vite/vite.sim.w

Use the new `inflight interface` modifier introduced by https://github.com/winglang/wing/pull/6197.

fix: use the new inflight interface modifier

---

dynamodb/README.md

* Add Docker as `prequisite` in README.md
As Docker is a requirement to run simulator locally, this PR adds it to the `prerequisite` list

docs(dynamodb): add docker prerequisite to DynamoDB README

---

tsoa/lib.js
tsoa/package-lock.json
tsoa/package.json

- tsup is great but it's an additional layer that we don't need, so switched to esbuild instead
- esbuild is invoked without creating a new process
- The full build is invoked with execFile and process.execPath to avoid shell overhead
With these changes, the existing sim test ran about 66% faster on my machine.

chore(tsoa): use esbuild directory and avoid extra process overhead

---

tsoa/package.json
tsoa/tfaws.w

There was an error saying that the class is missing a super() call. It looks like the implementation doesn't rely on extending cloud.Function, so I removed the `extends cloud.Function` code. I ran the unit test locally and on AWS and it passed on both.

fix(tsoa): does not compile with latest wing

---

postgres/README.md
postgres/lib.test.w
postgres/lib.w
postgres/pg.extern.d.ts
postgres/util.extern.d.ts
postgres/util.ts

Add `db.connection` as a preflight object so things like `db.connection.host`, `db.connection.port`, etc can be used as environment variables preflight.
In `sim`, wait for the database to listen before resolving the `port`. This means dependencies w ill only get initialized when the database is up.

feat(postgres): add preflight `db.connection`

---

test-all.sh

* Can specify specific wing binary to use for tests
* Explicitly use `bash` so `pipefail` will work
* Use custom `test.sh` when avaialble (for cdk8s)

chore: improve tests-all.sh

---

containers/api.w
postgres/lib.w
postgres/package-lock.json
postgres/package.json

* Hide internal nodes
* Add `Connection` link to inspector

feat(postgres): improve wing console ui

---

containers/README.md
containers/api.w
containers/forwarders.test.w
containers/helm.extern.d.ts
containers/helm.w
containers/package.json
containers/test/forwarders/Dockerfile
containers/test/forwarders/index.js
containers/workload.sim.w
containers/workload.tfaws.w
containers/workload.w

Introduce an API that allows forwarding various events to containers. Currently only implemented for `sim`.
The `workload.forward()` method returns an `IForward` object with a `fromXxx()` method for each supported handler type.
For example, this is how you can forward `cloud.Api` requests:
```js
let work = new containers.Workload(...);
let api = new cloud.Api();
api.get("/my_request", work.forward().fromApi());
```
You can pass an optional `route` and `method` to `forward()` in order to customize the behavior:
```js
work.forward(route: "/your_request", method: cloud.HttpMethod.PUT);
```

feat(containers): forwarding

---

ses/aws.extern.d.ts
ses/lib.w
ses/package-lock.json
ses/package.json
sns/lib.w
sns/package-lock.json
sns/package.json

missed those in the last PR...

feat: ses + sns icons

---

.github/workflows/close-stale.yaml
python/README.md
python/bucket.test.w
python/function.test.w
python/lib.w
python/package.json
python/queue.test.w
python/topic.test.w

chore(libs): rename python classes

---

python/package-lock.json
python/package.json
react/package-lock.json
react/package.json
react/sim.w

Follow up to https://github.com/winglang/winglibs/pull/277

chore: remove old syntax from winglibs (part 2)

---

dynamodb/dynamodb-client.w
dynamodb/dynamodb-types.w
dynamodb/dynamodb.sim.w
dynamodb/dynamodb.tf-aws.w
dynamodb/dynamodb.w
dynamodb/tests/update.test.w

It was not possible to partially update an item with the current methods (it might be possible with `transactWrite`, but it seemed counterintuitive to me). I added the `update` method to allow this.

feat(dynamodb): adding update call to dynamodb library

---

.github/workflows/canary.yaml
.mkrepo/main.w
checks/check.w
checks/package-lock.json
checks/package.json
fifoqueue/fifo-queue.aws.w
fifoqueue/package-lock.json
fifoqueue/package.json
github/lib.w
github/package-lock.json
github/package.json
messagefanout/lib.test.w
messagefanout/package-lock.json
messagefanout/package.json
messagefanout/platform/tf-aws.w
sagemaker/package-lock.json
sagemaker/package.json
sagemaker/sagemaker.test.w
tsoa/lib.extern.d.ts
tsoa/package-lock.json
tsoa/package.json
tsoa/tfaws.w

Fix several libraries to accommodate the breaking changes introduced in https://github.com/winglang/wing/pull/6903 and https://github.com/winglang/wing/pull/6219. 
Note: it looks like the cognito and python winglibs require more extensive changes so I was unable to fix them in this PR. I've opened separate tickets for them here: https://github.com/winglang/wing/issues/6923 and https://github.com/winglang/wing/issues/6924

fix: update libraries with Wing 0.79.0 compatibility

---

dynamodb/dynamodb.tf-aws.w
dynamodb/package-lock.json
dynamodb/package.json

The `compatibility.gsi.test.w` test was not working on AWS, so I added the configuration during table creation and the permission to access the global index.

fix(dynamodb): adding global index to tf-aws target

---

momento/cache.w
momento/package.json

I added the momento api key to the Terraform provider, making it mandatory for the MOMENTO_API_KEY environment variable to be configured, and fixed a bug that caused an exception when compiling for the tf-aws target.

fix(momento): adding momento api key to terraform provider 

---

.github/workflows/canary.yaml
.github/workflows/cloudv2-pull.yaml
.github/workflows/cloudv2-release.yaml
.github/workflows/pull-request-lint.yaml
.mergify.yml
README.md
cloudv2/.gitignore
cloudv2/LICENSE
cloudv2/README.md
cloudv2/counter-aws.extern.d.ts
cloudv2/counter-aws.ts
cloudv2/counter-aws.w
cloudv2/counter-sim.w
cloudv2/counter-types.w
cloudv2/counter.w
cloudv2/examples/counter.main.w
cloudv2/package-lock.json
cloudv2/package.json
cloudv2/test/counter/aws-counter.test.w
cloudv2/test/counter/dec.test.w
cloudv2/test/counter/inc.test.w
cloudv2/test/counter/initial.test.w
cloudv2/test/counter/peek.test.w
cloudv2/test/counter/set.test.w
cloudv2/util.w

Begin the process of migrating built-in `cloud` resource implementations from TypeScript to Wing. Only `sim` and `tf-aws` targets are in scope at the moment.
I put this into a new winglib just to avoid the initial issue of stuffing the source code into the bundled `winglang` package and wiring the compiler to auto-include those source files -- but eventually the code will probably go there.
The implementation of `Counter` is almost working, but I believe there's a lifting issue causing the tests to fail on AWS (https://github.com/winglang/wing/issues/6960) - I need to look into this.

feat: cloudv2

---

websockets/package-lock.json
websockets/package.json

Currently the canary tests are failing because the version of @winglibs/dynamodb it depends on is out of date.

chore(websockets): bump version to 0.3.11

---

bedrock/api.w
bedrock/bedrock.sim.w
bedrock/bedrock.tfaws.w
bedrock/package-lock.json
bedrock/package.json

Update the library using the features from https://github.com/winglang/wing/pull/6980 so that APIs intended to be private are now marked as `internal`.
Marked as a breaking change since it was possible for consumers to have used these internal APIs in the past (even if it was unintended).

fix(bedrock)!: hide internal APIs
